### ISSUE TITLE
您好 想问下最低配置的显卡要求是？

### ISSUE THREAD

**Issue by xiexinhua2006** [bilibili/ailab#10]
这边使用2060S 8G显存
scale=2，tile=4  原图分辨率4K 一打开就爆显存
还是说1080p的图才带的起来emm

**Comment by lj1995-computer-vision** [comment]
你好，我的开发机显卡是和你一样型号的显卡，4K的图像目前8G显存的确超不成，最近我在研究低显存模式，进一步通过牺牲一点速度来降低显存需求，精度没有损失。

**Comment by xiexinhua2006** [comment]
> 你好，我的开发机显卡是和你一样型号的显卡，4K的图像目前8G显存的确超不成，最近我在研究低显存模式，进一步通过牺牲一点速度来降低显存需求，精度没有损失。

好的，谢谢
