### ISSUE TITLE
请问Vapooursynth的Real-cugan推理代码是否还没支持Pro的模型。

### ISSUE THREAD

**Issue by NangInShell** [bilibili/ailab#107]
我自己测试from upcunet_v3_vs import RealWaifuUpScaler，只可以使用up2x-latest-conservative.pth模型，切换到pro模型后就会报错，不知道自己这边环境配置出的问题还是VS推理代码还没支持Pro的模型.
![image](https://user-images.githubusercontent.com/72263191/185026262-2d49378e-614c-4213-84e5-295bfb88c39a.png)

**Comment by manang666** [comment]
问题解决了，看了Pull requests里面的方法修改代码后可以运行pro的模型了。
