### ISSUE TITLE
超分视频时，使用moviepy导出音频会有音质损失

### ISSUE THREAD

**Issue by atkai** [bilibili/ailab#119]
发现超分之后的视频和原视频大小相比大不了多少的问题后，我检查了一下文件的参数，发现音频部分的采样率和码率降低了

**Comment by lj1995-computer-vision** [comment]
没办法，不是所有的视频格式都支持无损封装，因为本repo主旨也是超分，适配各种封装格式太过繁琐，望理解…
我做视频需要无损转音频轨的时候，一般用的小丸工具箱，能满足你的需求。
