### ISSUE TITLE
分享安装包建议用github release

### ISSUE THREAD

**Issue by AaronFeng753** [bilibili/ailab#13]
网盘限制太多, 目前的和彩云链接还失效了, 建议网盘分享同时用 github release

**Comment by splinter21** [comment]
我看看github release（但是我对它的墙内下载速度不是很放心）

**Comment by lj1995-computer-vision** [comment]
我看看github release（我对它的墙内下载速度不是很放心）

**Comment by AaronFeng753** [comment]
> 我看看github release（我对它的墙内下载速度不是很放心）

墙内处于玄学状态, 时快时慢, 有时根本打不开, 属于温水煮青蛙的状态, 快熟了

**Comment by AaronFeng753** [comment]
顺便问一下, caffe模型怎么用? 替换waifu2x-caffe Windows release里面的哪个模型?我试了替换好几个模型都提示无法打开您的标准模型, 或者没有任何效果

**Comment by AaronFeng753** [comment]
如果有可能的话求回复一下caffe模型的具体使用方法, 十分感谢

**Comment by AaronFeng753** [comment]
我用的是caffe的这个Windows版本 : https://github.com/lltcggie/waifu2x-caffe/releases/tag/1.2.0.4
替换了几个模型, 用CLI指定模型后, 都不可用或者没效果

**Comment by lj1995-computer-vision** [comment]
@AaronFeng753 waifu2x-caffe版本的话，网盘里的参数是和2x不降噪的按钮同名的，去model-cunet文件夹下，需要删掉（记得备份）原来scale2x的4个文件（json,caffemodel,bin等），用新的2个文件覆盖掉他原来的参数，然后选2x-不降噪，可以用你替换掉的real-cugan-caffe模型

**Comment by AaronFeng753** [comment]
@lj1995-computer-vision 成功了, 谢谢您! 祝您新年快乐, 万事如意!

**Comment by lj1995-computer-vision** [comment]
客气了~
