### ISSUE TITLE
当前模型似乎存在轻微色差现象

### ISSUE THREAD

**Issue by EcRal5t** [bilibili/ailab#16]
测试了多组图片均发现有此现象，表现为高饱和度部分 G、B 通道会比原图稍微低一点点（大概低 1~5 的样子，B 通道比较明显）

ESRGAN 也有这个问题，但轻微得可以忽略不计，而 CUGAN 就比 ESRGAN 显著一些。

**Comment by lj1995-computer-vision** [comment]
我们有观察到降噪和非降噪版参数有轻微的偏色现象。目前保守版参数没有观察到该现象。
