### ISSUE TITLE
About the license for this models

### ISSUE THREAD

**Issue by PINTO0309** [bilibili/ailab#17]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by lj1995-computer-vision** [comment]
https://github.com/bilibili/ailab/blob/main/Real-CUGAN/LICENSE

**Comment by PINTO0309** [comment]
Oh, I missed that. Thanks!
