### ISSUE TITLE
自制 GUI 图形用户界面 # I made a GUI for Real-CUGAN

### ISSUE THREAD

**Issue by AaronFeng753** [bilibili/ailab#18]
我自制的 图片视频GIF 超分辨率+补帧 GUI, 支持调用多种超分辨率和补帧方式

Waifu2x-Extension-GUI 已经从 v3.87.12-beta 版本开始支持Real-CUGAN了, 内置, 解压安装打开即用.

### GUI Download: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases

如果贵开发组以后出NCNN-Vulkan版本我也会尽量第一时间添加支持, ***或许可以能帮您省去您自己写UI的麻烦了***😁

#### 如果您觉得我这个GUI做的还行, 可以Readme加个链接吗? 谢谢

@lj1995-computer-vision

**Comment by caoli5288** [comment]
在？v我个解锁码？

**Comment by lj1995-computer-vision** [comment]
> 我自制的 图片视频GIF 超分辨率+补帧 GUI, 支持调用多种超分辨率和补帧方式
> 
> Waifu2x-Extension-GUI 已经从 v3.87.12-beta 版本开始支持Real-CUGAN了, 内置, 解压安装打开即用.
> 
> ### GUI Download: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases
> 如果贵开发组以后出NCNN-Vulkan版本我也会尽量第一时间添加支持, _**或许可以能帮您省去您自己写UI的麻烦了**_😁
> 
> #### 如果您觉得我这个GUI做的还行, 可以Readme加个链接吗? 谢谢
> @lj1995-computer-vision

@AaronFeng753 Readmd已更新，感谢支持！
