### ISSUE TITLE
有能用於Colab的方案嗎?

### ISSUE THREAD

**Issue by Arcelibs** [bilibili/ailab#22]
問就是沒有高階顯卡可以玩，想到了Google Colab一堆 K80，T4，P4和P100
不曉得能不能簡易的在colab上跑完後輸出儲存到雲端硬碟

**Comment by lj1995-computer-vision** [comment]
https://github.com/bilibili/ailab/blob/main/Real-CUGAN/colab-demo.ipynb
我上传了，您试试呢

**Comment by 1054028125** [comment]
这个colab-demo好像不能处理视频诶。。

**Comment by lj1995-computer-vision** [comment]
> 这个colab-demo好像不能处理视频诶。。

你可以参考inference_video.py写一个试试
