### ISSUE TITLE
有没有兴趣合作搞事情~

### ISSUE THREAD

**Issue by MegChai** [bilibili/ailab#26]
@lj1995-computer-vision  大佬你好 ( ・∀・)っ，这里是柴，一名老二刺螈 + 萌新 [UP](https://space.bilibili.com/7467858) . 同时也是国产深度学习框架 [天元 MegEngine](https://megengine.org.cn/) 小组的看门柴，目前我在四处溜达给 Megengine 找有趣的应用，尝试进行合作来验证框架的训练推理落地能力（不论是想做 demo 还是工业级部署都可以试试，旷视内部用的就是这套自研框架，有极致的性能优化，训推全流程中的很多坑都趟通了），感兴趣的话可以搓我的狗头。

话说这个 repo 以后是阿 B 以后放各种 AILab 模型的地方嘛，期待 ＼(￣▽￣)／.

**Comment by lj1995-computer-vision** [comment]
私下交流中
