### ISSUE TITLE
ncnn 版本

### ISSUE THREAD

**Issue by nihui** [bilibili/ailab#3]
你好呀！呼呼呼～
请问，会提供ncnn版本吗?
兼容amd/intel/macos/linux等平台

**Comment by lj1995-computer-vision** [comment]
对接中

**Comment by MegChai** [comment]
huihui 原来这么早就关注到了 = =

**Comment by tumuyan** [comment]
既然已经有为waifu2x-caffe玩家提供了两套参数，那么是否可以直接把caffe模型转换为ncnn模型，从而直接使用waifu2x-ncnn调用模型来使用呢？我不了解其中的细节，但是我试了试看上去caffe2ncnn工具只能转换prototxt格式的文件，无法处理protobin？

**Comment by lj1995-computer-vision** [comment]
已基本完成。
https://github.com/nihui/realcugan-ncnn-vulkan
