### ISSUE TITLE
最近的大包后缀有点问题

### ISSUE THREAD

**Issue by liyunlong2020** [bilibili/ailab#32]
最近的大包后缀为“.zip_2.001”需要改成“.zip.001”才能和“.zip.002”一起正常解压。希望后续更正。

**Comment by lj1995-computer-vision** [comment]
![releaseV3截图](https://user-images.githubusercontent.com/61866546/154851024-bea4dfe3-6262-4d1e-8bee-c9086fba88be.png)
不是吧
