### ISSUE TITLE
模型对于“长得像”Artifacts的内容来说存在过度处理

### ISSUE THREAD

**Issue by bbs3223474** [bilibili/ailab#33]
目前出于个人习惯，主要还是使用的waifu2x-caffe进行操作，不过在处理特定图片的时候，发现了一个很有意思的现象。
例如，Pixiv 作品ID：90795073，原图有一种很明显故意做出来的Artifacts，类似于纸张的模糊效果或者说相机噪点。也许是模型认为这种效果是真的噪点，且标准版自带denoise level 3，所以把它给抹掉了。
原图：
![QQ截图20220215080405](https://user-images.githubusercontent.com/4602466/153967648-8051d8d9-38ec-4e2a-a4d7-fd0cd3e81c4d.jpg)

放大后：
![QQ截图20220215080452](https://user-images.githubusercontent.com/4602466/153967668-a1e64e77-9dc6-4c2a-be4c-02b9711542cb.jpg)

个人建议如果能放出一个denoise level 0的waifu2x-caffe模型是最好的，或者希望能够实现waifu2x-caffe模型对于降噪度的自由调整。因为就本人而言，我是不喜欢将明显低于1080P且明显存在降质的图片拉到4K的，因此在图片原本信息量足够的情况下，不需要太多AI介入的部分。

**Edit：**
尝试使用了官方GUI进行操作，在2x-no-denoise的情况下，虽然脸部细节得到了更多保留，但原本的模糊纹理依旧存在严重涂抹痕迹，以至于出现色块现象（对比头发、胸口、手臂），因此判断并非单纯waifu2x模型默认3级降噪的问题。
![QQ截图20220215084351](https://user-images.githubusercontent.com/4602466/153971795-bcad450d-1f27-4a57-a0a0-8797c02dea15.jpg)

多次对比后，总体还是感觉waifu2x模型的处理会更加“过分”一些，甚至连一些虚化的东西都会被强行清晰化，而官方GUI则不存在这个问题。但对比waifu2x-caffe官方模型，人工噪点的处理还是会比Real-CUGAN更好一些。

**Comment by lj1995-computer-vision** [comment]
1、Caffe版本由于必须强制切割（由于Caffe框架较老，估计后续也不会有多少大佬去特别支持Caffe的推理吧），无法对整体进行主体区域和非主体区域的判断，是降噪强度最大的（无脑全部降）。模型的命名（降噪等级）是根据训练时加噪声的等级命名的，训练时对原图没有加噪声，会命名为no-denoise，但是不代表模型一点噪声都不会涂抹，事实上，只要是AI模型，都或多或少在高频上有一定损失（人工噪声也算是高频的一种），包括原版waifu2x-no-denoise
2、Real-CUGAN目前给出的模型中，噪声丢失幅度实测是这个排序（2x下）：
Caffe复现denoise3x-up2x>Caffe-无切割线版-up2x>denoise3x>denoise2x>denoise1x>no denoise>保守版
3、这张图原图有接近短边2000像素，对于大多数玩家，已经不需要再放大处理；作为hard case研究是可以的；
4、我们的模型确实没有见过带有大量人工噪声的图（训练集），这也是这类case无法处理的一个原因；
5、目前Real-CUGAN没有办法做到一键处理人工噪声和RGB通道偏移特效的图，也很少有其他的AI纯超分模型（特意设计分割等高级语义结构来分离噪声的混合模型结构，不称为纯超分模型，我目前没有看到过这类的开源工作）能做到完美保留人工噪声的效果，但是并不意味着这张图无解。我建议用传统算法直接拉伸这张图，如果实在需要精调，做到100分的话，建议将前景（初音未来）的线条区域，和其他区域（其他区域包括：初音未来非线条部分+背景所有）分别提取出来，用不同的算法处理后混合，例如，线条区域利用AI通道（因为Real-CUGAN的优秀的对模糊线条去模糊的特性），刻意模糊/刻意虚化/平坦区域利用传统上采样通道，噪声用纹理复制（如果纹理复制能成功，肯定比拉伸噪点好）通道，进行混合。
我随意列举一下需要注意到的，容易被修复坏的细节：
（1）我开始以为是全局加噪的，后来发现也不一定，例如左中侧的圆形斑点区域
（2）右下区域不仅有噪声，还有雾霾效果，要注意算法/模型不能增加了该区域的对比度
（3）下方的几个屏幕（里表情人，镜音等）的对RGB通道进行了人工像素偏移的区域
（4）初音的线条多处上色颜色溢出到线条边缘外
说了这么多，我觉得可能人肉PS比数字图像处理成本还更低了_(:3」∠)_
-------------------
总结一下：原图加入了多种人工"artifacts"来实现赛博朋克感的艺术效果，非常适合用来考验AI模型；几乎没有能一键处理该case的模型；如果要提升分辨率，建议强人工精细处理；原图分辨率足够高，已经满足绝大多数人的需求。

**Comment by bbs3223474** [comment]
感谢回复，值得一提的是，使用waifu2x-caffe的2x（没有denoise）或者noise1-2x模型可以保留原图的噪点并拉高分辨率，不过细节部分我没有去追究，主要对比了Artifacts的部分以及色偏的控制。
当然了，由于本身足够清晰（我只是想拉到4096x****级别的分辨率做壁纸而已），确实让AI介入的必要性不是很大。但个人认为仍值得一提的是，现在有很多画师会在画到布料、尤其是袜子时，故意加一些Aftifacts比如噪点、网纹、不规则的细微光斑、不规则的磨砂纹理等去模拟布料纹理，而不只是用纯色+阴影去表达。这些东西一直都是算法的障碍，真要跟原图抠起细节来也总是能发现这里那里不尽如人意的地方。只能希望有朝一日算法能训练到那个程度吧。

**Comment by Y-3-TEST** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lj1995-computer-vision** [comment]
> 感谢回复，值得一提的是，使用waifu2x-caffe的2x（没有denoise）或者noise1-2x模型可以保留原图的噪点并拉高分辨率，不过细节部分我没有去追究，主要对比了Artifacts的部分以及色偏的控制。 当然了，由于本身足够清晰（我只是想拉到4096x****级别的分辨率做壁纸而已），确实让AI介入的必要性不是很大。但个人认为仍值得一提的是，现在有很多画师会在画到布料、尤其是袜子时，故意加一些Aftifacts比如噪点、网纹、不规则的细微光斑、不规则的磨砂纹理等去模拟布料纹理，而不只是用纯色+阴影去表达。这些东西一直都是算法的障碍，真要跟原图抠起细节来也总是能发现这里那里不尽如人意的地方。只能希望有朝一日算法能训练到那个程度吧。

对于噪声使用放大算法本身就是有问题的，举个例子，假如画师加的噪声是一个点，采用放大算法可能出来是4个模糊的合在一坨的颜色较浅的点，好一点的模型放大出来是聚合在一起的比较锐利、颜色不浅的点，但是实际上，画师在更大的分辨率下直接渲染，应该是4个分开的颜色深的点（所以我会说纹理部分要用纹理复制）。Real-CUGAN的话可以试试保守版，我印象中，可能还会做出对噪声增强（这是错误的）的结果，而不是像denoise和no-denoise模型那样可能直接没了

目前还是一个通用的模型，更细粒化的处理，需要比较长时间的case积累、反馈与数据收集，这块我会一直关注的。有关动漫中常用的纹理、素材库，后期也有必要收集着。
最后感谢楼主提供的case！期待后续能有进一步的纹理优化和人工artifact保留，大家一起为动漫超分、修复添砖加瓦:muscle:
