### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by kobi2sc** [bilibili/ailab#34]
新手请见谅
运行出现FileNotFoundError: [Errno 2] No such file or directory: 'weights_v3/up2x-latest-no-denoise.pth'
要怎么改

#超分倍率
scale=2

#参数路径，可更换
model_path2 = "weights_v3/up2x-latest-no-denoise.pth"

model_path3 = "weights_v3/up3x-latest-denoise3x.pth"
model_path4 = "weights_v3/up4x-latest-denoise3x.pth"

以上是我填的一部分

**Comment by lj1995-computer-vision** [comment]
要去网盘文件夹另外的update_weights文件夹里面下载pth文件结尾的模型参数，然后model_path里面指定你需要用的这个参数的路径。

**Comment by kobi2sc** [comment]
刚下载完毕 丢到下载那边的C盘
config改
#超分倍率
scale=2

#参数路径，可更换
model_path2 =r"C:\Users\kobi\Downloads\up2x-latest-conservative"
model_path3 = "weights_v3/up3x-latest-denoise3x.pth"
model_path4 = "weights_v3/up4x-latest-denoise3x.pth"

执行后 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kobi\\Downloads\\up2x-latest-conservative'

**Comment by lj1995-computer-vision** [comment]
> 刚下载完毕 丢到下载那边的C盘 config改 #超分倍率 scale=2
> 
> #参数路径，可更换 model_path2 =r"C:\Users\kobi\Downloads\up2x-latest-conservative" model_path3 = "weights_v3/up3x-latest-denoise3x.pth" model_path4 = "weights_v3/up4x-latest-denoise3x.pth"
> 
> 执行后 FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kobi\Downloads\up2x-latest-conservative'

@kobi2sc 你win是设置了隐藏文件后缀的，r"C:\Users\kobi\Downloads\up2x-latest-conservative.pth"这样是对的

**Comment by kobi2sc** [comment]
哈哈难怪 可以了 谢谢你
