### ISSUE TITLE
480P老动画放大后的眼部的处理问题

### ISSUE THREAD

**Issue by ConstantineNo** [bilibili/ailab#36]
环境：
Windows10
GPU为1060 6G

参数：
scale=2
tile=2
模型为不降噪

当片源的眼部质量出问题或者说糊了之后，模型补充的效果变得很奇怪..

![vlcsnap-2022-02-16-15h01m42s471](https://user-images.githubusercontent.com/20835832/154214846-7e3a0edf-dd87-4539-ac88-5fdc4b58465d.png)

![vlcsnap-2022-02-16-15h01m42s471_2x](https://user-images.githubusercontent.com/20835832/154214806-b08d3270-cf2a-4626-9f37-5c8a32ede88a.png)

**Comment by lj1995-computer-vision** [comment]
符合预期。
超分算法要尊重事实。原画不画眼球，我们不能无中生有帮他画出眼球，这是违反画师意愿的。
