### ISSUE TITLE
内建字幕情况下 （字幕以外）画面会变得模糊

### ISSUE THREAD

**Issue by kobi2sc** [bilibili/ailab#40]
带有字幕（留意眼睛处）：
https://imgur.com/Crz6Qdu

没字幕（留意眼睛处）：
https://imgur.com/qzqITWj

原图
https://imgur.com/kOSSUsw

设定：
win10 pro
3060ti
scale=2
tile=3
nt=1
保守版

**Comment by lj1995-computer-vision** [comment]
属于已观察到的现象，字体更清晰所以被当做了主要聚焦区域清晰化，而画面被当做了背景，容易理解。
本仓库不负责字体相关逻辑，无法一键化。需要抠除字体区域特殊处理，或者使用不带内建字幕的raw处理。
