### ISSUE TITLE
有没有不单单对动漫的，对视频对照片等等

### ISSUE THREAD

**Issue by ihsz-OldFriend** [bilibili/ailab#41]
或者其他对视频的项目

**Comment by soldivelot** [comment]
要处理照片现在有[ESRGAN](https://github.com/xinntao/ESRGAN) [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) [SwinIR](https://github.com/JingyunLiang/SwinIR)，视频有[BasicVSR++](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/basicvsr_plusplus/README.md)，这个可能只针对anime

**Comment by chi2nagisa** [comment]
可以看看这个repo[Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI) 里面集成了数个能用的对视频的，对照片做超分的项目，不过会弹付费支持的弹窗。

**Comment by lj1995-computer-vision** [comment]
本仓库公开的模型针对动漫。其他的，楼上帮你回答了。
