### ISSUE TITLE
操作失败

### ISSUE THREAD

**Issue by SiMaLaoShi** [bilibili/ailab#43]
![image](https://user-images.githubusercontent.com/28924681/154838701-513e4c35-5b3a-4da6-bef9-a733fb700b8c.png)
真人图片就行，二次元图片就不行

**Comment by lj1995-computer-vision** [comment]
这个是由于真人图像的分辨率更高导致。一周内我们放出低显存模式。

**Comment by lj1995-computer-vision** [comment]
@SiMaLaoShi 试试updated20220220版本？
config里：
half写True
tile写5
cache_mode按顺序写0、1、2（直到显存够为止。如果2还不够，tile再往大得写）

**Comment by SiMaLaoShi** [comment]
更新后级没问题了
