### ISSUE TITLE
漫画字体放大得很奇怪

### ISSUE THREAD

**Issue by LyntNy4n** [bilibili/ailab#44]
如下图,分别是原图, 使用waifu2x 1倍降噪, 使用cugan 1倍降噪 放大的结果
虽然cugan在人物上效果比waifu2x好 但是字体不好读
![ori](https://user-images.githubusercontent.com/49772385/154907059-dff5f6cf-bd9c-4ed7-8316-e791e18c44c0.jpg)
![waifu2x](https://user-images.githubusercontent.com/49772385/154907071-ebd1c610-a9c9-4071-8a51-833e32a86e7d.jpg)
![cugan](https://user-images.githubusercontent.com/49772385/154907079-a2f7c349-5da7-4605-81f2-a546341c4931.jpg)

**Comment by lj1995-computer-vision** [comment]
模型没有加入文字训练，对文字不鲁棒属于已知现象。
现在文字分割技术很成熟。建议mask出文字部分bicubic/使用专门的文字超分算法，再blending。

**Comment by tumuyan** [comment]
> 现在文字分割技术很成熟。建议mask出文字部分bicubic/使用专门的文字超分算法，再blending。

可以推荐一些已经实用化支持中日文字的超分算法嘛？我搜了下似乎已经集成打包方便使用的只有HMS ML Kit
