### ISSUE TITLE
VapourSynth 导入后能否开启单卡多线程？

### ISSUE THREAD

**Issue by feaonal** [bilibili/ailab#45]
在VapourSynth导入后未发现线程的选项，请问是否能开启显卡的多线程？如果没有的话，希望大佬能够加入此模式。谢谢

**Comment by lj1995-computer-vision** [comment]
视频级对不同帧开多线程这个由vs控制的，https://github.com/bilibili/ailab/blob/main/Real-CUGAN/VapourSynth/simple-upcunet.vpy#L8
帧内多线程暂时不支持
开了不一定能带来显卡占用率的提升。
