### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by icecliffs** [bilibili/ailab#47]
![](https://bfs.iloli.moe/2022/02/3f94eb82501f3d1de978b859b1d2e62f.jpg)

**Comment by cht6688** [comment]
E:\realcugan>runtime\python runtime\inference234.py
Traceback (most recent call last):
  File "runtime\inference234.py", line 65, in <module>
    main()
  File "runtime\inference234.py", line 2, in main
    import torch,cv2, pdb, traceback,sys
  File "E:\realcugan\runtime\torch\__init__.py", line 135, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "E:\realcugan\runtime\torch\lib\shm.dll" or one of its dependencies.

E:\realcugan>pause
请按任意键继续. . .



**我这里也是报这个错误**

**Comment by lj1995-computer-vision** [comment]
@icecliffs @cht6688 你们看看runtime\torch\lib那个文件夹里面有shm.dll这个文件吗？

**Comment by lj1995-computer-vision** [comment]
以及大伙的系统cuda版本、显卡型号、win版本求一下

**Comment by cht6688** [comment]
一号机：
_C:\Users\chtd>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_19:03:51_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0_


![image](https://user-images.githubusercontent.com/56745121/155752173-b7dad819-50e1-4503-a513-91f746db8ba0.png)

_版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎6/‎26
操作系统内部版本	19043.1526
体验	Windows Feature Experience Pack 120.2212.4170.0_

![image](https://user-images.githubusercontent.com/56745121/155752993-0c59fe16-7151-43b2-86c8-8fa5d7ffe201.png)

还有台电脑 RTX2070 也是同样报错，如果需要的话我上去截图（
@lj1995-computer-vision

**Comment by cht6688** [comment]
> 以及大伙的系统cuda版本、显卡型号、win版本求一下
> 
> 哦对还有一个问题，你们的系统有自带python吗？

![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)

尝试过3.10 也是同样报错

**Comment by lj1995-computer-vision** [comment]
> > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > 哦对还有一个问题，你们的系统有自带python吗？
> 
> ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> 
> 尝试过3.10 也是同样报错

@cht6688 我把0226版上传到百度云了，你再看看呢？

**Comment by cht6688** [comment]
> > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > 哦对还有一个问题，你们的系统有自带python吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> > 尝试过3.10 也是同样报错
> 
> @cht6688 我把0226版上传到百度云了，你再看看呢？

我去尝试下，百度网盘下载太慢了

**Comment by cht6688** [comment]
> > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > 哦对还有一个问题，你们的系统有自带python吗？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> > 尝试过3.10 也是同样报错
> 
> @cht6688 我把0226版上传到百度云了，你再看看呢？

不过之前报错的是cu111不是cu100的版本

**Comment by lj1995-computer-vision** [comment]
> > > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > > 哦对还有一个问题，你们的系统有自带python吗？
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> > > 尝试过3.10 也是同样报错
> > 
> > 
> > @cht6688 我把0226版上传到百度云了，你再看看呢？
> 
> 不过之前报错的是cu111不是cu100的版本

@cht6688 和彩云和谷歌盘我也传了

**Comment by cht6688** [comment]
> > > > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > > > 哦对还有一个问题，你们的系统有自带python吗？
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> > > > 尝试过3.10 也是同样报错
> > > 
> > > 
> > > @cht6688 我把0226版上传到百度云了，你再看看呢？
> > 
> > 
> > 不过之前报错的是cu111不是cu100的版本
> 
> @cht6688 和彩云和谷歌盘我也传了

![image](https://user-images.githubusercontent.com/56745121/155828543-02741474-87d5-4435-a2b8-0725b10781d0.png)

图片放了还是报错
![image](https://user-images.githubusercontent.com/56745121/155828551-bebd0597-27c1-4385-a6a1-0509e6965a39.png)

**Comment by cht6688** [comment]
> > > > > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > > > > 哦对还有一个问题，你们的系统有自带python吗？
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)
> > > > > 尝试过3.10 也是同样报错
> > > > 
> > > > 
> > > > @cht6688 我把0226版上传到百度云了，你再看看呢？
> > > 
> > > 
> > > 不过之前报错的是cu111不是cu100的版本
> > 
> > 
> > @cht6688 和彩云和谷歌盘我也传了
> 
> ![image](https://user-images.githubusercontent.com/56745121/155828543-02741474-87d5-4435-a2b8-0725b10781d0.png)
> 
> 图片放了还是报错 ![image](https://user-images.githubusercontent.com/56745121/155828551-bebd0597-27c1-4385-a6a1-0509e6965a39.png)

![image](https://user-images.githubusercontent.com/56745121/155828992-55ee5c60-e7e1-4589-b7ad-5f98677172b4.png)
 
最初的 [Real-CUGAN release v3](https://github.com/bilibili/ailab/releases/tag/Real-CUGAN) 没有报错

**Comment by cht6688** [comment]
> > > > > > > 以及大伙的系统cuda版本、显卡型号、win版本求一下
> > > > > > > 哦对还有一个问题，你们的系统有自带python吗？
> > > > > > 
> > > > > > 
> > > > > > ![图像](https://user-images.githubusercontent.com/56745121/155753384-6c919931-0ec5-4b00-9b65-ce3d2995bdff.png)尝试过3.10 也是同样报错
> > > > > 
> > > > > 
> > > > > @cht6688 我把0226版上传到百度云了，你再看看呢？
> > > > 
> > > > 
> > > > 不过之前报错的是cu111不是cu100的版本
> > > 
> > > 
> > > @cht6688 和彩云和谷歌盘我也传了
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/56745121/155828543-02741474-87d5-4435-a2b8-0725b10781d0.png)
> > 图片放了还是报错![图像](https://user-images.githubusercontent.com/56745121/155828551-bebd0597-27c1-4385-a6a1-0509e6965a39.png)
> 
> ![图像](https://user-images.githubusercontent.com/56745121/155828992-55ee5c60-e7e1-4589-b7ad-5f98677172b4.png)
> 
> 最初的 [Real-CUGAN 版本 v3](https://github.com/bilibili/ailab/releases/tag/Real-CUGAN) 没有报错

@lj1995-computer-vision

**Comment by lj1995-computer-vision** [comment]
链接：https://pan.baidu.com/s/18budFv7rHMr8AG_HBMumkA 
提取码：u5b2 

@cht6688 这个版本应该可以用了？之前的0226可以删了

**Comment by cht6688** [comment]
> 链接：https://pan.baidu.com/s/18budFv7rHMr8AG_HBMumkA 提取码：u5b2
> 
> @cht6688 这个版本应该可以用了？之前的0226可以删了

![image](https://user-images.githubusercontent.com/56745121/155831553-267edab3-bf68-408a-95fe-cdef69ea327e.png)
我好了，记得发个release

**Comment by lj1995-computer-vision** [comment]
> > 链接：https://pan.baidu.com/s/18budFv7rHMr8AG_HBMumkA 提取码：u5b2
> > @cht6688 这个版本应该可以用了？之前的0226可以删了
> 
> ![image](https://user-images.githubusercontent.com/56745121/155831553-267edab3-bf68-408a-95fe-cdef69ea327e.png) 我好了，记得发个release （百度网盘太折磨人了，

已发新的release。感谢测试！
