### ISSUE TITLE
-1降噪条件下 某些图片反而变模糊

### ISSUE THREAD

**Issue by LyntNy4n** [bilibili/ailab#53]
使用的是ncnn版本 amd显卡
触发原因不清楚 整卷漫画偶尔会有几张图片出现这个情况 重复尝试依旧 换到-1以上的降噪就没有这个问题
使用-1降噪的主要原因是这个倍数的降噪对画风影响低,字体也不会变奇怪,还能消除原图中字体周围的噪点,使画面更干净
我只能贴几张有问题和没问题的图来说明
有该问题的原图:
![018](https://user-images.githubusercontent.com/49772385/156381656-284880bc-3c70-4666-b8c9-3df1c611af6b.jpg)
-1降噪:
![018_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156381918-53a30183-ad99-4924-a111-2a06ed58dca5.jpg)
有该问题的原图:
![077](https://user-images.githubusercontent.com/49772385/156382645-21126187-0e01-4c2c-82e7-b00ef4f3728f.jpg)
-1降噪:
![077_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156383237-96dad1d1-fc24-46c9-8606-4cf2bae1a463.jpg)
其他正常的原图:
![070](https://user-images.githubusercontent.com/49772385/156382810-fcf55111-ac41-48e6-817e-53e621a032ae.jpg)
-1降噪:
![070_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156382875-d465cabb-cdfd-40d0-8ce0-282cab75c152.jpg)

**Comment by lj1995-computer-vision** [comment]
> 使用的是ncnn版本 amd显卡 触发原因不清楚 整卷漫画偶尔会有几张图片出现这个情况 重复尝试依旧 换到-1以上的降噪就没有这个问题 使用-1降噪的主要原因是这个倍数的降噪对画风影响低,字体也不会变奇怪,还能消除原图中字体周围的噪点,使画面更干净 我只能贴几张有问题和没问题的图来说明 有该问题的原图: ![018](https://user-images.githubusercontent.com/49772385/156381656-284880bc-3c70-4666-b8c9-3df1c611af6b.jpg) -1降噪: ![018_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156381918-53a30183-ad99-4924-a111-2a06ed58dca5.jpg) 有该问题的原图: ![077](https://user-images.githubusercontent.com/49772385/156382645-21126187-0e01-4c2c-82e7-b00ef4f3728f.jpg) -1降噪: ![077_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156383237-96dad1d1-fc24-46c9-8606-4cf2bae1a463.jpg) 其他正常的原图: ![070](https://user-images.githubusercontent.com/49772385/156382810-fcf55111-ac41-48e6-817e-53e621a032ae.jpg) -1降噪: ![070_W2xEX_1x_-1n_Compressed_jpg](https://user-images.githubusercontent.com/49772385/156382875-d465cabb-cdfd-40d0-8ce0-282cab75c152.jpg)

@LyntNy4n 

你试试看ncnn的no-sync-mode（mode0）?应该会变锐利一些（看看会不会出现其他奇怪的问题？比如每块像素边缘有一圈折痕之类的）

或者模型路径选no-se这个（gap-sync-mode别选0，以及只有一个模型（应该是denoise参数0））
这个版本不带景深虚化保留的，直接对全局进行增强处理，不会因为景深误判维持模糊。

**Comment by LyntNy4n** [comment]
@lj1995-computer-vision

syncgap-mode设置为0时,不再有模糊的问题了,但是确实有些地方表现比较奇怪
原图:
![image](https://user-images.githubusercontent.com/49772385/156495643-ab912d3a-533a-4868-ab73-431583f01067.png)
syncgap-mode=0 , -1降噪 右上角变色:
![image](https://user-images.githubusercontent.com/49772385/156495699-3073b00c-ce7c-450c-9944-a7db4d91679d.png)
使用[Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI)会更奇怪:
![image](https://user-images.githubusercontent.com/49772385/156496154-65f5c492-aa10-4d9b-aa0c-3be173ec1c13.png)
而syncgap-mode设置为1(accurate sync)时,既不模糊也没有奇怪的问题了,就是处理比较慢:
![image](https://user-images.githubusercontent.com/49772385/156495811-69197235-37ff-4640-9688-3a63aa242dad.png)

使用no-se的话会完全改变画风(灰色阴影消失,网点去除不干净),所以不可用
![nose 0](https://user-images.githubusercontent.com/49772385/156496313-f6a4128e-caca-4ddd-90fb-d66b2b3f95a1.jpg)

**Comment by lj1995-computer-vision** [comment]
> @lj1995-computer-vision
> 
> syncgap-mode设置为0时,不再有模糊的问题了,但是确实有些地方表现比较奇怪 原图: ![image](https://user-images.githubusercontent.com/49772385/156495643-ab912d3a-533a-4868-ab73-431583f01067.png) syncgap-mode=0 , -1降噪 右上角变色: ![image](https://user-images.githubusercontent.com/49772385/156495699-3073b00c-ce7c-450c-9944-a7db4d91679d.png) 使用[Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI)会更奇怪: ![image](https://user-images.githubusercontent.com/49772385/156496154-65f5c492-aa10-4d9b-aa0c-3be173ec1c13.png) 而syncgap-mode设置为1(accurate sync)时,既不模糊也没有奇怪的问题了,就是处理比较慢: ![image](https://user-images.githubusercontent.com/49772385/156495811-69197235-37ff-4640-9688-3a63aa242dad.png)
> 
> 使用no-se的话会完全改变画风(灰色阴影消失,网点去除不干净),所以不可用 ![nose 0](https://user-images.githubusercontent.com/49772385/156496313-f6a4128e-caca-4ddd-90fb-d66b2b3f95a1.jpg)

@LyntNy4n 看来，gap-sync-mode=1/2/3 + -1降噪 会适合你。
2和3比1更快，可以一个个往上加，如果你觉得效果对你来说是无损的话，可以用更快的模式。
