### ISSUE TITLE
低显存显卡在设置tile后依旧爆显存

### ISSUE THREAD

**Issue by renbo12** [bilibili/ailab#54]
显卡为丽台t1000，显存4G，在设置tile=4，cache_mode=3后依旧爆显存
![微信图片_20220304112727](https://user-images.githubusercontent.com/45628617/156693742-0b07d260-bb54-43f1-ad68-3290c2d7217e.png)

**Comment by lj1995-computer-vision** [comment]
你的输入图像分辨率有多大？
tile4设置小了。4意味着整张图被切成4*4=16块，你可以算一下每一块的大小是多大。如果设置到每一块短边在128~256之间，4G显卡跑应该都是没问题的。另外和显存有关的一点是，half=True理论上比half=False省一半显存，效果上肉眼观感完全一致，速度差不多，只要显卡支持都建议设置为True。

**Comment by renbo12** [comment]
是3782*2521的，ok，明白了，意思是图片太大了
