### ISSUE TITLE
超分图片丢失细节

### ISSUE THREAD

**Issue by mouse9527** [bilibili/ailab#79]
![image](https://user-images.githubusercontent.com/34568564/170840041-b9e61500-b265-449c-a93e-71c75ee72291.png)
左边是原始图片，右边为超分后的图片。可以看到有很多点点被涂抹掉了(请原谅我不知道这些点点的专业名词😳

**Comment by dtlnor** [comment]
这是feature，不是bug（确定）

**Comment by mouse9527** [comment]
感谢！
