### ISSUE TITLE
[亲] upcunet_v3_vs.py & upcunet_v3.py 错误文件(html)上传：里面的“py”文件，内容其实是html代码

### ISSUE THREAD

**Issue by mrtaichi** [bilibili/ailab#83]
[亲] upcunet_v3_vs.py & upcunet_v3.py 错误文件(html)上传：里面的“py”文件，内容其实是html代码

首先，我要感谢bilibili的辛勤工作和加班，试图给我们带来这么好的东西。 我想指出 Pro 版本中的一些（可能的）错误。

[专业版] upcunet_v3_vs.py & upcunet_v3.py
这两个文件的全部内容都由 html 代码组成。
也许是错的。
请看一下。

[html.zip](https://github.com/bilibili/ailab/files/8845157/html.zip)

**Comment by feaonal** [comment]
文件下载的不对。去网盘里下，或者直接在代码首页打包成zip下载。

**Comment by mrtaichi** [comment]
> 文件下载的不对。去网盘里下，或者直接在代码首页打包成zip下载。

谢谢你。 我明白了。 这就是我一直在使用它的方式。 然而，即使 upcunet_v3_vs.py 在 4 天前更改，我还没有看到专业版的 vapoursynth 正在运行。 谁能告诉我，有没有办法让 CUGAN-Pro 版本的 vapoursynth 工作？

**Comment by feaonal** [comment]
> > 文件下载的不对。去网盘里下，或者直接在代码首页打包成zip下载。
> 
> 谢谢你。 我明白了。 这就是我一直在使用它的方式。 然而，即使 upcunet_v3_vs.py 在 4 天前更改，我还没有看到专业版的 vapoursynth 正在运行。 谁能告诉我，有没有办法让 CUGAN-Pro 版本的 vapoursynth 工作？

Real-CUGAN/VapourSynth/upcunet_v20220227_vs.py，有人进行了修改，在20220227版本中加入代码，载入Pro版的模型，我也是先使用的这个版本

**Comment by feaonal** [comment]
> > > > 文件下载的不对。去网盘里下，或者直接在代码首页打包成zip下载。
> > > 
> > > 
> > > 谢谢你。 我明白了。 这就是我一直在使用它的方式。 然而，即使 upcunet_v3_vs.py 在 4 天前更改，我还没有看到专业版的 vapoursynth 正在运行。 谁能告诉我，有没有办法让 CUGAN-Pro 版本的 vapoursynth 工作？
> > 
> > 
> > Real-CUGAN/VapourSynth/upcunet_v20220227_vs.py，有人进行了修改，在20220227版本中加入代码，载入Pro版的模型，我也是先使用的这个版本
> 
> 你的意思是当前的 upcunet_v20220227_vs.py 文件已经是 CUGAN-pro 版本了？ 如果没有，你能告诉我如何获取文件的更新版本（专业版）吗？

https://github.com/dtlnor/ailab/commit/2d5824673c70129e49de711a20197e642df39b63

**Comment by mrtaichi** [comment]
@feaonal 
非常感谢feaonal。 你帮了我很大的忙。

**Comment by mrtaichi** [comment]
> 当使用pro-no-denoise3x-up2x.pth并在config.py和VapourSynth的RealWaifuUpScaler中把half，tile，cache_mode和alpha设置为相同的值时，输出结果非常不同。
> 看来，只允许加载 CUGAN-pro 版 model的变化是不够的。

谢谢。 我一直在做实验。
