### ISSUE TITLE
能否加入与Anime4K的画质和性能对比？

### ISSUE THREAD

**Issue by ShinChven** [bilibili/ailab#9]
我一直在用 [Anime4K](https://github.com/bloc97/Anime4K) 实时观看超分辨率的动画。希望能看到 Real-CUGAN 与 Anime4K 的对比。

**Comment by lj1995-computer-vision** [comment]
您好，可能要让您失望了，目前以Real-CUGAN的性能，还不足以达到实时播放的水平，后续我们会进一步优化模型的速度。
之后我会抽空做和Anime4K的对比。
